[BACKLOG-37098] xul tag <image> :: Functional images don't provide te…
pentaho/pentaho-commons-xul pull request #215
Opened 2023-03-07 18:26 UTC by NJtwentyone

…xt alternative - GWT based Images

- impl for GwtImage.java
- refactor GwtToolbarbutton.java

2023-03-07 18:27 UTC, NJtwentyone commented on gwt/impl/pom.xml
> +      <groupId>com.google.gwt.gwtmockito</groupId>
change to gwt's mockito in order to mock Gwt's client.ui related classes

2023-03-07 18:27 UTC, buildguy commented
### :x: Build failed in 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-03-07 18:27 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> -import org.pentaho.gwt.widgets.client.utils.StringUtils;
old class `org.pentaho.gwt.widgets.client.utils.StringUtils` is deprecated. the new class has the same functions

2023-03-07 18:28 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +  public GwtImage( Image image, ImageUtil imageUtil ) {
constructor used for unit testing

2023-03-07 18:28 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +          // do nothing
added default cause, removing previous sonarqube issue

2023-03-07 18:29 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +    // first checks "pen:imagealttext" then other attributes
more or less post processing attribute

2023-03-07 18:31 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtToolbarbutton.java
> -  // WCAG default value for attribute 'alt' when image doesn't alternative text
logic is moved to `ImageUtil.java`

2023-03-07 18:31 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtToolbarbutton.java
> +      button = new ToolbarToggleButton( imageUtil.setImageDefaults( new Image() ) );
refactoring class, moved to `ImageUtil.java`

2023-03-07 18:32 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtToolbarbutton.java
> -    if ( image != null && StringUtils.isEmpty( image.getAltText() ) ) {
logic moved to `ImageUtil.java`

2023-03-07 18:32 UTC, NJtwentyone commented on gwt/impl/src/test/java/org/pentaho/ui/xul/gwt/tags/GwtToolbarbuttonTest.java
> -    // not using certain keywords to prevent UnsupportedOperationException: ERROR: GWT.create()
logic moved to `ImageUtil.java` and thus testing moved to `ImageUtilTest.java`

2023-03-07 18:34 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/util/ImageUtil.java
> + * General class to handle GWT Image operations mostly related to WCAG 2.1 requirements.
Created utility class instead of adding to parent class `AbstractGwtXulComponent.java`. I'm anticipating have to use this code in other places. Also, easier to test this isolated class and the logic is includes.

2023-03-07 18:57 UTC, NJtwentyone commented
> Details

We won't be able to get wingman to build off wcag for this repository. Because wingman is trying to build `master` branch on https://github.com/pentaho/pentaho-commons-gwt-modules and not `wcag` branch. The `wcag` branch has new classes and methods.

Proof of successful build:
![Screen Shot 2023-03-07 at 1 51 32 PM](https://user-images.githubusercontent.com/2119761/223522232-ffeb31ad-a65b-4d12-b2e4-ee61d2f04fbc.png)



Proof of unit tests working that I modified/created:


![Screen Shot 2023-03-07 at 1 56 11 PM](https://user-images.githubusercontent.com/2119761/223523426-e42660cf-8824-4907-91b8-3cca7f1ea786.png)

2023-03-07 19:10 UTC, peterrinehart approved these changes

2023-03-08 19:02 UTC, dcleao requested changes

2023-03-08 19:50 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +    return ( image != null ) ? image.getAltText() : null;
No. I'm not. never hurts to be protective.

2023-03-08 20:17 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +    String alternativeText = imageUtil.getAltText( this, srcEle );
Yes you followed the code correctly. 

I completely understand the super.getAttributes() should be called already.  I even left a comment referencing the `super.init()`

I'm future proofing my code, incase AbstractGwtXulComponent.int(), AbstractGwtXulComponent.setAttribute() or AbstractGwtXulComponent.getAttributeEnumName() logic changes. Their logic scatter to remove "pen:" and  calls toUpperCase(). 

There are very little unit test cases and integration tests for this project/module. For gwt/impl folder my test cases are the first ones.

This is my attempt to cover all or most scenarios. That explains some redundancy.

2023-03-08 20:21 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/util/ImageUtil.java
> +  public static final String ATTRIBUTE_IMAGE_ALT_TEXT = "imagealttext";
We do not validate the xul files using a XSD schema, but there is/was a XUL spec.

You can still find bits of the XUL spec online using the web archive. For example, here's the main XUL reference page: https://web.archive.org/web/20171209141146/https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/XUL_Reference.

2023-03-09 10:55 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/util/ImageUtil.java
> +    if ( image != null && StringUtils.isEmpty( image.getAltText() ) ) {
Sure, I guess you can see this as a matter of style.
I prefer being strict and making it clear that nulls are not allowed (e.g. via "NotNull" annotation or Java doclets).

2023-03-09 10:59 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +    return ( image != null ) ? image.getAltText() : null;
You have stated your preference, but did not provide an argument, for or against.

2023-03-10 19:29 UTC, buildguy commented
### :x: Build failed in 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-03-10 19:31 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/util/ImageUtil.java
> +  public static final String ATTRIBUTE_IMAGE_ALT_TEXT = "imagealttext";
I updated the code based on your code review conversation, please see commit https://github.com/pentaho/pentaho-commons-xul/commit/b72234ced74dc9dc031ea901db8a018030a4009a

2023-03-10 19:31 UTC, NJtwentyone commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java
> +    String alternativeText = imageUtil.getAltText( this, srcEle );
I updated the code based on your code review conversation, please see commit https://github.com/pentaho/pentaho-commons-xul/commit/b72234ced74dc9dc031ea901db8a018030a4009a

2023-03-13 10:53 UTC, dcleao approved these changes

2023-03-13 14:24 UTC, merged