[BACKLOG-37246] Page Zoom (AA) - Base XUL/GWT Dialog Classes - XML Attributes
pentaho/pentaho-commons-xul pull request #232
Opened 2023-04-24 12:32 UTC by varuntangirala

@pentaho/wcag, Please review

2023-04-24 12:34 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-232/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-26 05:09 UTC, soagarwal1 commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    dialog.setResponsive( this.responsive );
Use setAttribute() method instead of directly using or remove setAttribute method if not used

2023-04-26 11:29 UTC, dcleao requested changes

2023-04-26 11:29 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    dialog.setResponsive( this.responsive );
Please remove the `this` from `this.responsive`, matching the style of the other field references.

2023-04-26 11:29 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    dialog.setResponsive( this.responsive );
Could you clarify? Proposed code seems appropriate — to use the GWT DialogBox class' `setResponsive` method instead of lower level APIs directly accessing the DOM.

2023-04-26 11:45 UTC, soagarwal1 commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    dialog.setResponsive( this.responsive );
This piece of code makes no sense it we are not using it. 
https://github.com/pentaho/pentaho-commons-xul/pull/232/files#diff-946448218933bc83d0054b70a33295bc9df7009ff3eaa7e6ba37daba56bc4732R491-R506

I understand that this is not the right place to do, we should do it in the setter methods in https://github.com/pentaho/pentaho-commons-xul/pull/232/files#diff-946448218933bc83d0054b70a33295bc9df7009ff3eaa7e6ba37daba56bc4732R440-R466

2023-04-26 11:47 UTC, soagarwal1 commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    dialog.setResponsive( this.responsive );
This piece of code is not used then if we are going to use it in this way.
https://github.com/pentaho/pentaho-commons-xul/pull/232/files#diff-946448218933bc83d0054b70a33295bc9df7009ff3eaa7e6ba37daba56bc4732R440-R466

2023-04-26 11:58 UTC, soagarwal1 commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    dialog.setResponsive( this.responsive );
Cleared how it is being used with @varuntangirala help . Closing, Proposed changes are good.

2023-04-27 11:17 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-232/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-27 11:35 UTC, dcleao requested changes
All good, otherwise.

2023-04-27 11:35 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
> +    setSizingMode( SizingMode.valueOf( sizingMode.toUpperCase() ) );
Ideally, these String overloaded methods would do something like:
```java
setSizingMode( StringUtils.isEmpty(sizingMode) ? null : SizingMode.valueOf( sizingMode.toUpperCase() ) );
```

2023-04-27 11:43 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-232/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-04-27 13:27 UTC, dcleao approved these changes

2023-04-28 06:49 UTC, hv-vamsi approved these changes

2023-04-28 07:42 UTC, soagarwal1 approved these changes

2023-04-28 07:42 UTC, merged