[BACKLOG-37828] Added keyboard navigation and focus visibility
pentaho/pentaho-commons-xul pull request #254
Opened 2023-06-23 13:16 UTC by jsaraf

@pentaho/wcag Please review

2023-06-23 13:18 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-254/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-26 10:05 UTC, hv-vamsi commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
> +    selectRowInTable();
can you add if ( !isHierarchial() ) here

2023-06-27 06:55 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-254/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-27 07:13 UTC, jsaraf commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
> +    selectRowInTable();
Added.

2023-06-27 07:15 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-254/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-27 10:29 UTC, dcleao requested changes

2023-06-27 10:29 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTextbox.java
> -        }
In this case, I think it would be preferable to keep the oncommand functionality in the `GwtTextbox` and to remove the property from the XUL markup instances instead. All themes would be affected, and that seems ok.

2023-06-27 10:29 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
> +      selectRowInTable();
Given this code exists within the `populateTable` method, `isHierarchical` should always be `false`.

2023-06-27 10:29 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
> +  private void selectRowInTable() {
Perhaps would be better to use the plural for rows and using a different verb, e.g. `updateSelectedRowsInTable`.

2023-06-27 10:29 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
> +    selectRowInTable();
Unless there is an actual reason for doing it this way, I'd prefer that updating the internal state would be settled before firing any events (in which external parties may change course). As such, would call `selectRowInTable` at line 1129.

2023-06-27 11:08 UTC, jsaraf commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTextbox.java
> -        }
Opted to remove this code since no other occurrences were found for this particular functionality within Pentaho organization code after a GitHub search. If you insist on the change, will rollback.

2023-06-27 14:40 UTC, dcleao commented on gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTextbox.java
> -        }
That's fine, then.

2023-06-28 11:07 UTC, buildguy commented
### :white_check_mark: Build finished in 1m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-254/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-06-28 12:45 UTC, dcleao approved these changes

2023-07-06 05:40 UTC, merged